import Pkg
#Pkg.add("Flux")
Pkg.add("ONNX")
Pkg.add("Images")
Pkg.add("Random")
Pkg.add("FileIO")
Pkg.add("Conda")
Pkg.add("PyCall")
Pkg.build("PyCall")
Pkg.add("JLD2")
Pkg.add("StatsKit")
Pkg.add("ImageMagick")
Pkg.add("DataFrames")
Pkg.add("Interpolations")
Pkg.add("ImageFiltering")
Pkg.add("CSV")
#Pkg.add("https://github.com/OpenMendel/OrdinalMultinomialModels.jl")
using Conda
Conda.add("zeroc-ice36-python",channel="ome")
Conda.add("omero-py",channel="ome")
Conda.add("zarr",channel="conda-forge")
Conda.add("scikit-image",channel="conda-forge")
